# Generated by Django 2.0.9 on 2025-03-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='state/'),
        ),
    ]
