# Generated by Django 2.0.9 on 2025-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0003_userregister_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_place',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
