# Generated by Django 2.0.9 on 2025-03-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0004_tourist_place_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
