# Generated by Django 2.0.9 on 2025-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0005_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
