# Generated by Django 2.0.9 on 2025-03-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0006_auto_20250329_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourist_place',
            name='price_per',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
