# Generated by Django 2.0.9 on 2025-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0007_auto_20250329_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gst_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
