# Generated by Django 2.0.9 on 2025-03-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0008_reservation_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
