# Generated by Django 2.0.9 on 2025-04-26 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0009_reservation_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trip_plan.Confirmation'),
            preserve_default=False,
        ),
    ]
