# Generated by Django 2.0.9 on 2025-04-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0010_feedback_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reservation',
        ),
    ]
