# Generated by Django 2.0.9 on 2025-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_plan', '0011_remove_feedback_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
